from resources.gui.widgets.group_box import GroupBox
from resources.gui.widgets.button import ButtonWidget
from resources.gui.widgets.text_label import TextLabelWidget
from resources.gui.widgets.entry import EntryWidget
from resources.gui.widgets.text_widget import TextWidget
from resources.gui.widgets.radiobutton import RadioButton
from resources.gui.widgets.checkbox import Checkbox
from resources.gui.widgets.combobox import ComboBox
from resources.gui.widgets.slider import Slider
from resources.gui.widgets.progress_bar import ProgressBar
from resources.gui.widgets.spin_box import SpinBox
from resources.gui.widgets.calendar import CalendarWidget
from resources.gui.widgets.tabele import TableWidget